item_dict = [{"name":"Jergens Smoothing Aloe", "price":5.99, "stock":100, "Type of Product": "Lotion", "image": "https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/daily-moisturizers/JER-CC-Hands-3oz-400x500.png?fmt=png-alpha&wid=320"}, 
             {"name":"Jergens Cloud Creme", "price":7.00, "stock":100, "Type of Product": "Lotion", "image": "https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/daily-moisturizers/JER-CC-Hands-3oz-400x500.png?fmt=png-alpha&wid=320"}, 
             {"name":"Jergens Dry Skin", "price": 6.00, "stock":100, "Type of Product": "Lotion", "image":"https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/daily-moisturizers/Hand-and-Body-Cream-thumb.png?fmt=png-alpha&wid=320"}, 
             {"name":"Jergens Secret Citrius", "price": 5.99, "stock":100, "Type of Product": "Lotion", "image":"https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/daily-moisturizers/soothing-aloe-thumb.png?fmt=png-alpha&wid=320"}, 
             {"name":"Jergens Secret Lavender", "price": 5.00, "stock":100, "Type of Product": "Lotion", "image":"https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/butter/JER_Citrus_BodyButter_7oz-400x500.png?fmt=png-alpha&wid=320"},
             {"name":"Jergens Firming Glow Set", "price": 7.00, "stock":100, "Type of Product": "Lotion", "image":"https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/butter/JER_Lavender_BodyButter_7oz-400x500.png?fmt=png-alpha&wid=320"},
             {"name":"Jergens Daily Moisterizer Glow Set", "price": 7.00, "stock":100, "Type of Product": "Lotion", "image":"https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/natural-glow/56822_JNG_Daily_Group_600x800.png?fmt=png-alpha&wid=320"}, 
             {"name":"Jergens Instant Sun", "price": 4.99, "stock":100, "Type of Product": "Lotion", "image":"https://kao-h.assetsadobe3.com/is/image/content/dam/sites/kaousa/www-jergens-com/images/master/products/natural-glow/56822_JNG_Daily_Group_600x800.png?fmt=png-alpha&wid=320"}]

employee_id = {"Traven": 123, "Alexis": 456, "Abby": 789, "Guest":000}